apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 10m
 #suspend: true
  path: ./apps/jenkins
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx
    - name: persistence
    - name: my-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: jenkins
      namespace: jenkins
  timeout: 6m0s
  validation: client
  wait: true
