#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: flux-system
#  namespace: flux-system
#spec:
#  prune: false
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-gpg
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  verify:
    mode: head
    secretRef:
      name: pgp-public-keys
