apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-oidc-proxy
  namespace: flux-system
spec:
  interval: 11h54m31s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kube-oidc-proxy
  dependsOn:
    - name: ingress-nginx
    - name: my-secrets
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-oidc-proxy
      namespace: kube-oidc-proxy
  timeout: 2m0s
