apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- flux-system-deploy-branch.yaml
- slack-notification.yaml
- gitno-hephy-pro-ingress.yaml
- git-webhook-receiver.yaml
- linkerd-demos-git-webhook-receiver.yaml
- image-webhook-receiver.yaml
- podinfo-image-webhook-receiver.yaml
- on-call-webapp-alert.yaml
