apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  summary: moo-cluster
  eventSources:
    # - kind: GitRepository
    #   name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmChart
      name: '*'
    - kind: HelmRepository
      name: '*'
    # - kind: ImageUpdateAutomation
    #   name: '*'
    # - kind: ImagePolicy
    #   name: '*'
    - kind: ImageRepository
      name: '*'
