apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10h30m
  retryInterval: 10m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb
  prune: true
  wait: false
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-operator-controller-manager
      namespace: metallb-system
    - apiVersion: metallb.io/v1beta1
      kind: MetalLB
      name: metallb
      namespace: metallb-system
    - apiVersion: metallb.io/v1alpha1
      kind: AddressPool
      name: moo-cluster
      namespace: metallb-system
