apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvpn-as
  namespace: flux-system
spec:
  interval: 15m
  timeout: 8m
  releaseName: openvpn
  targetNamespace: openvpn
  storageNamespace: openvpn
  dependsOn:
    - name: internal-ingress
      namespace: ingress-nginx
    - name: public-ingress
      namespace: ingress-nginx
  chart:
    spec:
      chart: ./charts/openvpn-as
      version: '^0.2.0'
      sourceRef:
        kind: GitRepository
        name: kingdonb-helm-charts-1
        namespace: flux-system
      interval: 40m
  valuesFrom:
  - kind: Secret
    name: vpn-admin-superuser
    valuesKey: user
    targetPath: openvpn.admin.user
  - kind: Secret
    name: vpn-admin-superuser
    valuesKey: password
    targetPath: openvpn.admin.password
  - kind: Secret
    name: vpn-user-kingdon
    valuesKey: user
    targetPath: openvpn.users[0].user
  - kind: Secret
    name: vpn-user-kingdon
    valuesKey: password
    targetPath: openvpn.users[0].password
  values:
    service:
      type: LoadBalancer
    persistence:
      existingClaim: openvpn-openvpn-as-state
    ingress:
      gui:
        enabled: true
        hostName: vpn.hephy.pro
        ingressClassName: public
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          # kubernetes.io/ingress.class: nginx
          # kubernetes.io/tls-acme: "true"
        tls:
          enabled: true
          secretName: vpn-hephy-pro-tls
      admin:
        enabled: true
        hostName: vpn-admin.hephy.pro
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          # kubernetes.io/ingress.class: nginx
          # kubernetes.io/tls-acme: "true"
        tls:
          enabled: true
          secretName: vpn-admin-hephy-pro-tls
