apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: deis
  namespace: flux-system
spec:
  interval: 47h59m28s
  suspend: false
  path: ./apps/hephy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: my-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: deis-controller
      namespace: deis
  timeout: 3m0s
