apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 47h59m28s
  retryInterval: 10m
  suspend: false
  path: ./apps/gitea
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: gitea
      namespace: gitea
  timeout: 2m0s
