apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 5m0s
  timeout: 2m0s
  suspend: false
  prune: true
  wait: true
  path: ./apps/gitea
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: gitea
      namespace: gitea
