apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 5m0s
  timeout: 2m0s
  suspend: true
  prune: true
  path: ./apps/argocd
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: certificates
