apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 47h59m28s
 #suspend: true
  path: ./apps/argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # dependsOn:
  #   - name: ingress-nginx
  #   - name: persistence
  #   - name: my-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: argocd-server
      namespace: argocd
  timeout: 6m0s
