apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-infra
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 5m0s
  timeout: 2m0s
  path: ./infrastructure/linkerd
  suspend: false
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: openvpn
