apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-infra
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 10m
  suspend: false
  path: ./infrastructure/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  dependsOn:
    - name: openvpn
