---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: okteto-flux
  namespace: flux-system
spec:
  targetNamespace: flux
  storageNamespace: flux
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  releaseName: flux
  chart:
    spec:
      version: ^1.11.1
      chart: flux
      sourceRef:
        kind: HelmRepository
        name: okteto-apps
  interval: 40m0s
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
        - kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: flux
            namespace: flux
            annotations:
              fluxcd.io/automated: "false"
              fluxcd.io/tag.flux: regex:^master-5c6a9644$
              fluxcd.io/tag.flux-recv: semver:0.6.0
        - kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: flux-memcached
            namespace: flux
            annotations:
              fluxcd.io/automated: "false"
              fluxcd.io/tag.memcached: regex:^1.6.10-alpine$
        - kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: flux-helm-operator
            namespace: flux
            annotations:
              fluxcd.io/automated: "false"
              fluxcd.io/tag.flux-helm-operator: semver:1.4.0
  values:
    flux:
      image:
        repository: docker.io/fluxcd/flux-prerelease
        tag: master-5c6a9644
      git:
        branch: own-branch
        url: ssh://git@github.com/kingdonb/flux-getting-started.git
      registry:
        excludeImage: index.docker.io/jenkins/*,index.docker.io/library/*,index.docker.io/okteto/*,docker.io/weaveworks/*,index.docker.io/weaveworks/*,index.docker.io/grafana/*,index.docker.io/datawire/*,quay.io/keycloak/*,index.docker.io/kingdonb/*,index.docker.io/hephy/*,index.docker.io/fluxcd/*,index.docker.io/prom/*,index.docker.io/buoyantio/*,index.docker.io/kiwigrid/*,cr.l5d.io/linkerd/*,index.docker.io/rancher/*,quay.io/jetstack/*,docker.l5d.io/buoyantio/*,quay.io/metallb/*,quay.io/kiwigrid/*,127.0.0.1:5555/*,ghcr.io/fluxcd/*,k8s.gcr.io/metrics-server/*,ghcr.io/linuxserver/*,k8s.gcr.io/ingress-nginx/*,k8s.gcr.io/kube-state-metrics/*,quay.io/prometheus/*,quay.io/prometheus-operator/*,k8s.gcr.io/coredns/*,k8s.gcr.io/kube-proxy
      rbac:
        create: true
      serviceAccount:
        create: true
      clusterRole:
        create: true
    secret: df10802a8a2bd4ddacf0323838f495810ce61748
    helm-operator:
      rbac:
        create: true
      serviceAccount:
        create: true
      clusterRole:
        create: true
