---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system-rw
  namespace: flux-system
spec:
  interval: 15m0s
  ref:
    branch: main
  secretRef:
    name: flux-system-rw
  url: ssh://git@gitea-ssh.gitea.svc.cluster.local/kingdon/jenkins-infra
