---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: jenkins
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kingdonb-jenkins
  filterTags:
    pattern: '^lts-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

