apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
## Basic Jenkins installation
- helmrepo.yaml
- helmrelease.yaml
# - namespace.yaml

## Flux Automations
- apps-jenkins-automation.yaml
- kingdonb-jenkins-registry.yaml
- jenkins-policy.yaml

## Flux read-write GitRepo for image automation
- flux-system-rw-gitrepo.yaml

## Jenkins charts gitrepo for chart debugging
# - jenkins-charts-gitrepo.yaml
