apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 11h59m11s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metrics-server
  prune: false
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
