apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-extras
  namespace: flux-system
spec:
  interval: 75m
  retryInterval: 4m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/flux-system-extras
  dependsOn:
    - name: ingress-nginx
    - name: certificates
    - name: my-secrets
  prune: true
  wait: true
