apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  interval: 47h59m28s
  timeout: 2m0s
  retryInterval: 3m0s
  path: ./apps/podinfo
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

