---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kingdonb-podinfo
  filterTags:
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
