---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kingdonb-podinfo
  policy:
    semver:
      range: ^6.0.0

