---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: monitoring
  url: https://github.com/kingdonb/flux2
