apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-legacy
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 5m
  timeout: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/flux-legacy
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flux
      namespace: flux
    - apiVersion: apps/v1
      kind: Deployment
      name: flux-memcached
      namespace: flux
    - apiVersion: apps/v1
      kind: Deployment
      name: flux-helm-operator
      namespace: flux
