apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-legacy
  namespace: flux-system
spec:
  interval: 11h54m31s
  retryInterval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/flux-legacy
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flux
      namespace: flux
    - apiVersion: apps/v1
      kind: Deployment
      name: flux-memcached
      namespace: flux
    - apiVersion: apps/v1
      kind: Deployment
      name: flux-helm-operator
      namespace: flux
  timeout: 2m0s
