apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      containers:
        - name: podinfod
          image: docker.io/kingdonb/podinfo:master-79a02744-1635361353 # {"$imagepolicy": "flux-system:podinfo-dev"}
      imagePullSecrets:
        - name: regcred
