kind: Secret
apiVersion: v1
metadata:
    name: buoyant-cloud-id
    namespace: buoyant-cloud
    labels:
        app.kubernetes.io/part-of: buoyant-cloud
type: Opaque
data:
    id: ENC[AES256_GCM,data:y44/37G3gqjzNaBha0R8YAgYUgDr50tR,iv:bXjLst4iXUF1H1cv1rGk2+bkwsQIGOTl+C7sQcjD4oM=,tag:AKOrI7UeDbb1WJSuK8s19Q==,type:str]
    key: ENC[AES256_GCM,data:PSCjgWBR4KcmT+xkzRLVMqS4urnWCIAGq2lNy3L+r2sFNELtCRd5c/z0rjInXX85kWhM9CXVtt6QZe0l,iv:4qrvA9Ep+SgKul1gSalBBLJVboxozKMeqBKBy1Yn+KU=,tag:7cOdfJQK8DMUVQvTPbVJ/w==,type:str]
    downloadKey: ENC[AES256_GCM,data:/rcrk6lC822TmQGRTmzPjpFiSsh+F3wnxbRpKDCfYEGXkPHcBiEdS/JJlZBtVv5j250sSPk0B8LpkMcG,iv:iHw+7DpEvvI7ZBbvEA42S/DJnollbJEdgTe+2AEFIlY=,tag:2YIQMVskoT/QfCBZHg7hVg==,type:str]
    name: ENC[AES256_GCM,data:9CMWNwJ2ZBaDa5qouon5Rg==,iv:8r+ce7W8Lou39j9xEGOPxiCqcZ2429exzdyKUNm0R/E=,tag:3HMN8Th/f7klIg6rOhEqHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-04T03:24:21Z"
    mac: ENC[AES256_GCM,data:S3brvE6AgB7t4qytZlZ7/fzkFipDSiWN2GLg2eUgZiB5LFkBMqx1HFm8ZGxgcPVqjpNlmtlUeCPacPxV7/uGQXRi+6xEOP/AmtyxbUjeruim6L9sWt8h57LZVOZm88KDHoIpBQu3z4ZUR5+OEAwL2S3rsWGbZTBT/joaC36ACE4=,iv:bBNfxbPN9t5/rprLzsaRWyIC/qWb/pMhDane3mFvsEU=,tag:ek1gn9K0MRmqML+6w76gXw==,type:str]
    pgp:
        - created_at: "2021-11-04T03:24:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMAQ//Y1jA4ZOh7XEZ8HZXhVwpeoVfMXWaJ22f0qlK5i2iphOF
            BE6f5ePuak8PmBArmvqLx9JFk+1ukCI3dshHtrHg2BLEnRzTumUBSWyblFjs5zXj
            pJDJF63YBmBIc88vtNHNr8Tl2ePM4FHcuEN94wet5/GlDhb+GtgKSPNqGsO2OjfX
            NBW9IA/8pffK8MuNQHZcsfnIHGsqsy1YW5B8UUTpFdAPkDWOH4LmUSSLA7rlZ8rL
            cA0wWJNnDC8eIMhHX3rqQJV3w287528tD6AFgBVGZQIvQ6zQEJ1niwqlGsShdYFu
            jOxUjI3F1ZXSD+rMPKgcC4/N8Uq1rRvQP8l3wT7GTQLOCkiX5vbU00mSIE8+8+/f
            C7MmEPN6mWd931SupqWT/FU7N8vLku+BOkRlY3AQAXfqjqXKV1P6Vl3cD2FNAE5c
            6KJEMZyXG4BZ5NiycLt1+BE/DZAHYbLVqHW99anLRUX8M+brc9VpvxXFom4nUGOK
            djw+JHelRZ8FDXRMB+eIIYdTeIg0NpnpEBCOvmtlooGF88GEjkSTOUbEBvdrZpwg
            iKtmtUer3eBVEpuor86JZmlgPW2wmoKhoYtvzgc64haJy7SHBrufki4sTz/BaMng
            KYIWEhB0SXKVDJjcEizD96BmKM6GKqKnz82OhBfXmLuaPSQcsH7r1OM5OME6ZXbS
            XgGkN1zOizuJozJWEQaMhwTsIh/eosxnRi5ByXQOv59LRR+35mOgSxwUryjFIJfI
            J3WbD5ZiL1lsn1oVu7TItf0EJ+edphRShaFFIFnSELmXvmDE7XLymqrGdO1eghA=
            =varY
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
