apiVersion: v1
data:
    DOCKER_REPO_PASSWORD: ENC[AES256_GCM,data:u7iMnyfqir7gL/YW,iv:SNiQO93qH4hORMQg46Um44q8Ui/24QKdjoNyoXIvTjY=,tag:3UEDxjfD12Cfb8TZz9t54w==,type:str]
    DOCKER_REPO_USER: ENC[AES256_GCM,data:DzNwNNUf+wC9E8nw,iv:EQLK57zIaEwzVyb8c2D1HuZLZwKxu0Avx45HLWYYO30=,tag:xmT/l+SrlDCrIrMInt52yQ==,type:str]
kind: Secret
metadata:
    name: docker-registry-admin
    namespace: jenkins
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-24T19:59:35Z"
    mac: ENC[AES256_GCM,data:jDkrQJFzNKzniY12sJzE2T0NM1E5bAEp3tRpCSFg6kx7tcNOnxSgSMMnIO/new9cF6WtfsySBMCdvgNMsiJHfQF4yvow70Vlfj499bzf8U69+zSDDLTOguYuPo41AcoP3O+fKFq15/slhCNJNr8fHhMLY9cL14SMDDEYCSU5ZW4=,iv:1jECILNQdFrfPMuw+vDJMfT5pl6DOXK6eS9VVZNltxw=,tag:JGzCph5HjSTt/2iUqrJfTA==,type:str]
    pgp:
        - created_at: "2021-08-24T19:59:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMAQ//Z5Dg0Ii/QxwzshfHkoD8G+YLk7En1rbAhbExWpQWrrYL
            K3FNudTMMc+fuI8LYbKF74pU+x17TnLQ9uNDyhsmfOhqnRUIdPSOsBUIRfro4rQW
            GaJ3o3ULStSrCBfjqjpeXpxPgQSQ4ce+GsNPIg8QYbbxHKCOGP5ZyYrlsBPxXg2u
            whwsIhxvoeepdkRbxAhFFvp6yWOiTD9VcZQ5AAT6UiPcV+M78ErDHGFSvZNIjWGT
            lNJ0Lly5l50HS/xkYaG/n8K+7+6mzt5A8WriYE4/FWLGfSdSe7rgqBFrORuxM7w8
            PFkMvHXKCq8ziopZyTA6svFGvfagMWOIYwNIEz69SvAqKTJRuGX7fiVHWlqjEiws
            nYH8oEzXEBPiwLrUxD/RNwGf3OmrWEZYSnJWi5DhQCayZtQ5oAH+8dY/wu1cSIYS
            /DJWzrQHivfBvWVOwFb4yt4x6/zYUnyPjCMv06Tcbw3bp4QPIJePYfE7yxR45c/3
            xQ6MtJYgn7Ef98iuAMjF949VspOCvWQWUUFUH6rlabvVuHY3mi45qgYdHNDUYqaD
            IUmYFZja9xL+z9A5GyzSZhzEvY6bh2ppTQtVCwLpowBtNkb553jIItvc3SPAddr9
            UADUSsBaCez4ZNgcwFGZ08WkGka2dh8edF2ICNC4efnW8dR61m5L2nHFOROsgo3S
            XgF5OBBxHGtbIQzi3MZZGSgA0/C55nq06VpQzLtu5TqEU0EljsvJHLHOjXuMGccI
            VtLN3sV2FA0wG5zPX4xAd/monpkaq4XVpE8KvxPQk3e3Co6wJ+opoK3oAN2yKPk=
            =/s9A
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
