apiVersion: v1
kind: Secret
metadata:
    labels:
        dev.okteto.com: "true"
    name: okteto-regcred
    namespace: flux
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:qXx24CrZfCld3xBF6LceZU/U6FHPBDjUuvX6i63m0iENSO5YliH5E1SrbKLKffs80pcUgMeKQSNR4dEGRWPPwZDn1TKSixAxlLof2Sspq+Ggg/6u0GscZzZPupiF7OYzt78hXQ2Lg0uLNkhbVH4h0td98Gu585qU0tLKI/8fegpBwF7BeU8eubbGgFhIhaFLYkIlHMPjMPUzbHMGb4trP23RLCkflxfgNhuUSA==,iv:xa0E3lxDu9tv7EYQ4aceIZa0bgsGgXqRzSwweYY0oEQ=,tag:FSaoszYVkgN67CrlFswetA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-30T16:32:55Z"
    mac: ENC[AES256_GCM,data:D7F60AGHxx2wbCGs1Vau2+zy7TLIpSMH8MhOeJWCIyvo+tIlkFVlln2Jgc0sNJNFK7lA9R9xPTC+vaiNksWJQ1zquwZITwfWoMBOIEGWtRZZlOXAhj1GYQeAU/VONTJaXB87BZndvLbVzwbs1kwl5A+43ilWolQp+vF6cpYSj78=,iv:9DST63xG/Iu/wCySCI5s6aGPM2U1duao7wX4iySketA=,tag:45CbAvGUf5x1gFv6bB2E+A==,type:str]
    pgp:
        - created_at: "2021-10-30T16:32:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMARAAoPTxDSQBnL1mIg3TdR84z8I2tpKnBhPRfpKQ5XAENpGY
            huhVUMHkZdNxt3SDbWf59JzLo+oIqVexS1n/C7c4p7Gdj+0IrDMDZrN6zAtzGHLJ
            2w02lNUOu7uOLausK0jtfBFhnoJ2+srlUGU1cnIiCWfK3j4hFX0QWTKuOtzbt4p/
            5t07ocgC9KaZ5xlXyce8SRALEJdmD3a7uxP+jKFsDX/b3SIbrEB/NOjfB8K7zo47
            zVYij3EwzDIO0BXwnQYsZla5TV6roZn2u+LhSdgN1urFsqrHQSVrxgEoHtfZ859Z
            1WsqjG4Q6/wnq/4G/V3/QuqBtD1CK/O+Fw53U/2suRsEwdg26VxOnBfWkB68NsRI
            k6NhUmeVaWBV5CYuzqSw1bfXJ4CntVsObEviFObEW6eeE5DNQUOzChbCvY1rX1QV
            H53yUyh5ddALQqdDIkSwGZGn1p4s1nSNksAxd2xy0ZYbbM3H4S9QDfF6icEvW2AN
            DPzTqKDklhGDXvVHuzu4l7TbL9CBMkQ5LlO6hVyTJOZFoRgC5/s+BxDUzw+wQ+NS
            7+D5ZscSOL9zoM+ZJrUvoJCKWPpnu71gt7SAox5ylLhHrNT8aQMDqm39IW4LleLX
            mFMyoSK129v655vmCPkVuCnnH4kmF8+FwttcT0rVwrqxa+VWGeAoMbWAcpYW9X7S
            XgFltdHlJSJ1VAX9EIz8RWYhAHEHCMSNm3Qa6zAC6nsSL19fdZU+qvEKPqCGhE/1
            RzcR4b7YUTKBHTOcUfrBNhBKAnWLXwh0YP/W2SyJhuzZ1BcKbpRV/8rMa0mlq5Q=
            =7QA3
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
