apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: persistence
  namespace: flux-system
spec:
  interval: 11h14m21s
  suspend: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./persistence
  prune: false
  validation: client
  timeout: 5m0s
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: local-path-provisioner
      namespace: local-path-storage
