apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/local-path-provisioner
  prune: false
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: local-path-provisioner
      namespace: local-path-storage
