---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: linkerd-demos
  namespace: flux-system
spec:
  interval: 60m0s
  ref:
    branch: main
  url: https://github.com/kingdonb/linkerd-demos

