---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-secrets-branch
  namespace: flux-system
spec:
  interval: 40m0s
  ref:
    branch: secrets
  url: https://github.com/kingdon-ci/jenkins-infra
