---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  #suspend: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 30m0s
  retryInterval: 1m
  path: ./secrets/moo-cluster
  prune: false
  sourceRef:
    kind: GitRepository
    name: my-secrets-branch
