apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-ingress
  namespace: ingress-nginx
spec:
  interval: 45m
  releaseName: ingress-internal
  chart:
    spec:
      chart: ingress-nginx
      version: '^4.0.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 15m
  values:
    controller:
      extraArgs:
        enable-ssl-passthrough: ""
        ingress-class: internal
      ingressClassResource:
        name: internal
        default: true
