apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: public-ingress
  namespace: ingress-nginx
spec:
  interval: 36h45m10s
  timeout: 2m0s
  releaseName: ingress-public
  dependsOn:
    - name: internal-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: '^4.0.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 15m
  values:
    controller:
      extraArgs:
        enable-ssl-passthrough: ""
        ingress-class: public
      electionID: public-ingress-leader
      ingressClassResource:
        name: public
        default: false
        controllerValue: "k8s.io/ingress-nginx-public"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
