apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea-srv
  namespace: flux-system
spec:
  interval: 5m
  releaseName: gitea
  targetNamespace: gitea
  storageNamespace: gitea
  chart:
    spec:
      chart: gitea
      version: '^4.0.3'
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 40m
  values: {}
