apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea-srv
  namespace: flux-system
spec:
  suspend: true
  interval: 36h45m10s
  releaseName: gitea
  targetNamespace: gitea
  storageNamespace: gitea
  chart:
    spec:
      chart: gitea
      version: '^4.0.3'
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 40m0s
  values:
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        service:
          DISABLE_REGISTRATION: true
    persistence:
      enabled: true
      existingClaim: data-gitea-0
    postgresql:
      persistence:
        enabled: true
        existingClaim: data-gitea-postgresql-0
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        #kubernetes.io/ingress.class: internal
      hosts:
        - host: gitea.hephy.pro
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-hephy-pro
          hosts:
            - gitea.hephy.pro
