apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: openvpn
  namespace: flux-system
spec:
  interval: 10m0s
 #suspend: true
  path: ./apps/openvpn-as
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx
    - name: persistence
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: openvpn-openvpn-as
      namespace: openvpn
  timeout: 5m0s
