apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 73m0s
  retryInterval: 6m0s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/keycloak
  dependsOn:
    - name: my-secrets
    - name: certificates
    - name: ingress-nginx
  prune: true
  wait: true
