apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/kingdon-ci/jenkins-infra'
    path: infrastructure/cert-manager
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
