apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-cluster
spec:
  destination:
    name: ''
    namespace: flux-system
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/moo-cluster/flux-system
    repoURL: 'https://github.com/kingdon-ci/jenkins-infra'
    targetRevision: main
  project: default

