apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/kingdon-ci/jenkins-infra'
    path: apps/gitea
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitea
