apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-oidc-proxy-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/kingdon-ci/jenkins-infra'
    path: infrastructure/kube-oidc-proxy
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-oidc-proxy
