apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  - argocd-app.yaml
  - cert-manager-app.yaml
  - cert-manager-issuers.yaml
  - flux-system-app.yaml
  - gitea-app.yaml
  - ingress-app.yaml
  - jenkins-app.yaml
  - keycloak-app.yaml
  - kube-oidc-proxy-app.yaml
  - local-path-app.yaml
  - metallb-app.yaml
  - metallb-instances.yaml
  - metrics-server-app.yaml
  - openvpn-as-app.yaml
  - podinfo-app.yaml
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: argocd-secret
  $patch: delete
