apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path
spec:
  project: default
  source:
    repoURL: 'https://github.com/kingdon-ci/jenkins-infra'
    path: infrastructure/local-path-provisioner
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-path-storage
